title: Open Source i den offentlige sektor
logo: /assets/img/jmk.png

author:
  name: Jan Maack Kjerbye
  github: JanMaackKjerbye
  
description: Reflektioner om open source i den offentlige sektor

theme: jekyll-theme-minimal
